language: node_js
node_js:
  - "12"
env:
  global:
    - USER="travis-node-browser-webdriver"
    - EMAIL="travis-node-browser-webdriver@github.com"
script:
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git remote rm origin
  - git remote add origin https://${GITHUB_TOKEN}@github.com/DevSide/node-browser-webdriver.git
  - node index.js
branches:
  only:
    - master
